services:

  nginx:
    image: nginx:alpine
    container_name: food-nginx
    ports:
      - "8095:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - order-api
    networks:
      - food-network

  order-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-api
    environment:
      DB_HOST: localhost
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - food-network

  db:
    image: postgres:16-alpine
    container_name: food-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - food-network

networks:
  food-network:
    driver: bridge

volumes:
  postgres-data: